server:
  port: 1990

#mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://98.159.99.170:3306/a0622154721?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: a0622154721
    password: df1d6d60
  mvc:
    static-path-pattern: /**

#模板引擎
thymeleaf:
  suffix: .html
  prefix: classpath:/templates/
  enabled: true
  cache: false

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

quartzCron:
  demo: 0/5 * * * * ?
